apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# DISABLED: Application temporairement désactivée
# resources:
#   - main.yaml
metadata:
  annotations:
    flux.weave.works/ignore: "true"